# eta correlation

# OBS: rodei antes script1.RMD e depois script2.R

df1$PostMateralismCategorial <- as.factor(df1$PostMaterialistIndex)
df2$PostMateralismCategorial <- as.factor(df2$PostMaterialistIndex)
df3$PostMateralismCategorial <- as.factor(df3$PostMaterialistIndex)
df4$PostMateralismCategorial <- as.factor(df4$PostMaterialistIndex)
df5$PostMateralismCategorial <- as.factor(df5$PostMaterialistIndex)
str(df1$PT)
str(df1$Ideologia)
str(df2$Ideologia)
str(df1$SEX)
str(df2$SEX)
options(scipen=999)
library(lsr)
model1a <- aov(MR1 ~ PostMateralismCategorial, data = df1)
etaSquared(model1a)
model1b <- aov(MR1 ~ PT, data = df1)
etaSquared(model1b)
model1c <- aov(MR1 ~ Ideologia, data = df1)
etaSquared(model1c)
model1d <- aov(MR1 ~ SEX, data = df1)
etaSquared(model1d)
model2a <- aov(MR1 ~ PostMateralismCategorial, data = df2)
etaSquared(model2a)
model2b <- aov(MR1 ~ PT, data = df2)
etaSquared(model2b)
model2c <- aov(MR1 ~ Ideologia, data = df2)
etaSquared(model2c)
model2d <- aov(MR1 ~ SEX, data = df2)
etaSquared(model2d)
model3a <- aov(MR1 ~ PostMateralismCategorial, data = df3)
etaSquared(model3a)
model3b <- aov(MR1 ~ PT, data = df3)
etaSquared(model3b)
model3c <- aov(MR1 ~ Ideologia, data = df3)
etaSquared(model3c)
model3d <- aov(MR1 ~ SEX, data = df3)
etaSquared(model3d)
model4a <- aov(MR1 ~ PostMateralismCategorial, data = df4)
etaSquared(model4a)
model4b <- aov(MR1 ~ PT, data = df4)
etaSquared(model4b)
model4c <- aov(MR1 ~ Ideologia, data = df4)
etaSquared(model4c)
model4d <- aov(MR1 ~ SEX, data = df4)
etaSquared(model4d)
model5a <- aov(MR1 ~ PostMateralismCategorial, data = df5)
etaSquared(model5a)
model5b <- aov(MR1 ~ PT, data = df5)
etaSquared(model5b)
model5c <- aov(MR1 ~ Ideologia, data = df5)
etaSquared(model5c)
model5d <- aov(MR1 ~ SEX, data = df5)
etaSquared(model5d)

